# Generated by Django 2.2.5 on 2019-10-17 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20190924_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=26)),
                ('last_name', models.CharField(default='', max_length=26)),
                ('email', models.EmailField(default='', max_length=100)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=26)),
                ('last_name', models.CharField(default='', max_length=26)),
                ('email', models.CharField(default='', max_length=50)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('size', models.IntegerField(default=1)),
                ('student', models.ManyToManyField(to='app.Student')),
                ('tutor', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=26)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ManyToManyField(to='app.Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer1', models.CharField(default='', max_length=200)),
                ('correct1', models.BooleanField(default=False)),
                ('answer2', models.CharField(default='', max_length=200)),
                ('correct2', models.BooleanField(default=False)),
                ('answer3', models.CharField(default='', max_length=200)),
                ('correct3', models.BooleanField(default=False)),
                ('answer4', models.CharField(default='', max_length=200)),
                ('correct4', models.BooleanField(default=False)),
                ('current_quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_quiz', to='app.Quiz')),
                ('quiz', models.ManyToManyField(to='app.Quiz')),
            ],
        ),
    ]
